<?php

/**
 * Implements hook_entity_view().
 */
function documentation_export_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {

  //echo('<b>Content types</b>');
  //echo '<br>';
  //$types = \Drupal::entityTypeManager()
  //  ->getStorage('node_type')
  //  ->loadMultiple();
  //foreach ($types as $type) {;
  //  echo($type->get('name') . ' - ' . $type->get('description')) . '<br>';
  //  foreach (\Drupal::entityManager()->getFieldDefinitions('node', $type->get('type')) as $field_name => $field_definition) {
  //    if (!empty($field_definition->getTargetBundle())) {
  //      echo $field_definition->getName() . ' ' . $field_definition->getDescription() . '<br>';
  //    }
  //  }
  //  echo '<br>';
  //  echo '<br>';
  //}
  //echo '<br>';
  //echo('<b>Paragraphs types</b>');
  //echo '<br>';
  //$types = \Drupal::entityTypeManager()
  //  ->getStorage('paragraphs_type')
  //  ->loadMultiple();
  //foreach ($types as $type) {
  //  echo($type->get('label') . ' - ' . $type->get('description'));
  //  echo '<br>';
  //}
//
  //echo '<br>';
  //echo('<b>Vocabularies</b>');
  //echo '<br>';
  //$types = \Drupal::entityTypeManager()
  //  ->getStorage('taxonomy_vocabulary')
  //  ->loadMultiple();
  //foreach ($types as $type) {
  //  echo($type->get('name') . ' - ' . $type->get('description'));
  //  echo '<br>';
  //}
  //die();
}
